version: '3.7'
services:
  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mysql_dev
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    restart: always
    networks:
      local-network:
        ipv4_address: 172.28.5.11

  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.3-fpm}
    container_name: wordpress_dev
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    depends_on:
      - mysql
    restart: always
    networks:
      local-network:
        ipv4_address: 172.28.5.12

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx_dev
    ports:
      - '${NGINX_PORT:-8001}:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      local-network:
        ipv4_address: 172.28.5.13

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_dev
    ports:
      - '${PMA_PORT:-8002}:80'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}      
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always
    networks:
      local-network:
        ipv4_address: 172.28.5.14

#  adminer:
#    image: adminer
#    container_name: adminer_dev
#    restart: always
#    links:
#      - mysql
#    ports:
#      - '${ADMINER_PORT:-8003}:8080'
#    networks:
#      local-network:
#        ipv4_address: 172.28.5.15
networks:
    local-network:
      name: local-network
      driver: bridge
      ipam:
        driver: default
        config:
         - subnet: 172.28.5.0/24
